"""Obligation library, regulatory-change feed and VIP catalog (seed content).

IMPORTANT: everything here is DEMO content. Every template carries verified=0 until a
legal/compliance reviewer signs it off. penalty_sar is an *indicative* per-occurrence
exposure used only to make the dashboard meaningful; published statutory maxima, where
known, are kept as text in penalty_note and are NOT used in totals.
"""

ALL = ["hotel", "hospital", "company"]

# scope: 'branch' -> one instance per applicable branch; 'employee' -> per employee document
TEMPLATES = [
    # ---------------- HR & labour (all sectors) ----------------
    dict(code="HR-WPS", title="رفع ملف حماية الأجور الشهري", authority="وزارة الموارد البشرية — مدد",
         category="الموارد البشرية", scope="branch", packs=ALL, recurrence_months=1, lead_days=5, severity=3,
         penalty_sar=10000, penalty_note="",
         fix_steps=["اعتمد كشف رواتب الشهر في نظام الرواتب قبل نهاية الشهر",
                    "صدّر ملف الأجور وارفعه عبر منصة مدد",
                    "راجع العاملين غير المطابقين (فروقات الأجر أو بيانات الحساب البنكي) وصحّحها",
                    "احفظ إيصال التحويل البنكي وتقرير الامتثال كدليل"],
         evidence="تقرير حماية الأجور + إيصال التحويل البنكي", vip_code="VIP-PAYROLL", source_url=""),
    dict(code="HR-GOSI", title="سداد اشتراكات التأمينات الاجتماعية", authority="المؤسسة العامة للتأمينات الاجتماعية",
         category="الموارد البشرية", scope="branch", packs=ALL, recurrence_months=1, lead_days=5, severity=3,
         penalty_sar=8000, penalty_note="",
         fix_steps=["افتح بوابة المنشآت في التأمينات الاجتماعية",
                    "راجع فاتورة الاشتراك الشهرية وطابقها مع عدد العاملين والأجور المسجّلة",
                    "سدّد الفاتورة عبر سداد قبل تاريخ الاستحقاق",
                    "حمّل إيصال السداد واحفظه"],
         evidence="فاتورة الاشتراك + إيصال سداد", vip_code="VIP-PAYROLL", source_url=""),
    dict(code="HR-NITAQAT", title="مراجعة نسبة التوطين (نطاقات)", authority="وزارة الموارد البشرية — قوى",
         category="الموارد البشرية", scope="branch", packs=ALL, recurrence_months=1, lead_days=7, severity=3,
         penalty_sar=20000, penalty_note="انخفاض النطاق يوقف خدمات المنشأة (تأشيرات، نقل خدمات، أجير).",
         fix_steps=["افتح لوحة نطاقات في منصة قوى وسجّل النسبة الفعلية",
                    "قارن بالنسبة المطلوبة لنشاط المنشأة وحجمها",
                    "حدّد الفجوة بعدد الموظفين المطلوب توطينهم",
                    "ضع خطة توظيف أو تحويل ضمن مهلة المعالجة وسجّلها"],
         evidence="لقطة لوحة نطاقات + خطة المعالجة", vip_code="VIP-NITAQAT", source_url=""),
    dict(code="HR-QIWA", title="توثيق عقود العمل في قوى", authority="وزارة الموارد البشرية — قوى",
         category="الموارد البشرية", scope="branch", packs=ALL, recurrence_months=3, lead_days=14, severity=2,
         penalty_sar=5000, penalty_note="",
         fix_steps=["استخرج قائمة العقود غير الموثقة من قوى",
                    "وثّق كل عقد وأرسله للموظف للقبول",
                    "تابع العقود المعلّقة حتى اكتمال التوثيق"],
         evidence="تقرير العقود الموثقة", vip_code="VIP-PAYROLL", source_url=""),
    dict(code="HR-OSH", title="مراجعة السلامة والصحة المهنية واللياقة الطبية", authority="وزارة الموارد البشرية",
         category="الموارد البشرية", scope="branch", packs=ALL, recurrence_months=12, lead_days=45, severity=2,
         penalty_sar=10000, penalty_note="",
         fix_steps=["حصر المهن عالية الخطورة في الفرع",
                    "تأكد من اللياقة الطبية لشاغلي هذه المهن",
                    "وثّق التدريب والشهادات وتواريخ التجديد"],
         evidence="سجل اللياقة الطبية والتدريب", vip_code=None, source_url="https://saudicomplianceinstitute.com/en/blogs/news/hospitality-compliance-2026-saudi-occupational-health-rules"),
    # ---------------- Hotels ----------------
    dict(code="HR-WORKERDATA", title="تحديث بيانات العاملين (كل 3 أشهر)", authority="وزارة السياحة",
         category="الموارد البشرية", scope="branch", packs=["hotel"], recurrence_months=3, lead_days=14, severity=3,
         penalty_sar=20000,
         penalty_note="مارس 2026: صدرت 84 إجراءً رقابيًا بحق منشآت ضيافة بسبب هذا البند (صحيفة سعودي غازيت).",
         fix_steps=["حدّث بيانات جميع العاملين، بمن فيهم عمالة شركات التشغيل، في منصة وزارة السياحة",
                    "تأكد من المؤهلات والخبرات المسجلة",
                    "احتفظ بإيصال التحديث"],
         evidence="إيصال تحديث بيانات العاملين", vip_code="VIP-WORKERDATA",
         source_url="https://www.lexismiddleeast.com/news/2026-03-18_21/en"),
    dict(code="LIC-MOT", title="ترخيص منشأة الإيواء السياحي", authority="وزارة السياحة",
         category="التراخيص", scope="branch", packs=["hotel"], recurrence_months=12, lead_days=60, severity=3,
         penalty_sar=50000,
         penalty_note="الحد الأقصى المنشور: حتى مليون ريال أو الإغلاق بحسب المخالفة (الوزارة أغلقت 25 منشأة في مكة خلال شهر واحد).",
         fix_steps=["تأكد من تطابق الأنشطة المرخصة مع النشاط الفعلي (التفاوت سبب شائع للرفض)",
                    "جهّز المستندات: السجل التجاري، شهادة الدفاع المدني، رخصة البلدية",
                    "قدّم طلب التجديد عبر منصة الوزارة",
                    "علّق الترخيص في مكان ظاهر"],
         evidence="الترخيص ساري المفعول", vip_code="VIP-LIC",
         source_url="https://gulfnews.com/world/gulf/saudi/saudi-arabia-closes-25-of-mecca-hotels-for-breaching-tourism-regulations-1.500212039"),
    # ---------------- Hospitals ----------------
    dict(code="LIC-MOH", title="ترخيص المنشأة الصحية", authority="وزارة الصحة",
         category="التراخيص", scope="branch", packs=["hospital"], recurrence_months=12, lead_days=60, severity=3,
         penalty_sar=50000, penalty_note="",
         fix_steps=["راجع اشتراطات الترخيص للفئة (مستشفى/مركز)",
                    "جهّز المستندات وقوائم الكوادر المرخصة",
                    "قدّم طلب التجديد وسدّد الرسوم"],
         evidence="الترخيص ساري المفعول", vip_code="VIP-HEALTHLIC", source_url=""),
    dict(code="ACC-CBAHI", title="اعتماد سباهي", authority="المجلس المركزي لاعتماد المنشآت الصحية",
         category="الجودة والاعتماد", scope="branch", packs=["hospital"], recurrence_months=36, lead_days=180, severity=3,
         penalty_sar=100000, penalty_note="",
         fix_steps=["نفّذ تقييمًا ذاتيًا مقابل المعايير الحالية",
                    "عالج الفجوات وأغلق الإجراءات التصحيحية",
                    "احجز زيارة التقييم قبل انتهاء الاعتماد"],
         evidence="شهادة الاعتماد وتقرير آخر زيارة", vip_code="VIP-HEALTHLIC", source_url=""),
    dict(code="LIC-WASTE", title="ترخيص التخلص من النفايات الطبية", authority="المركز الوطني لإدارة النفايات",
         category="التراخيص", scope="branch", packs=["hospital"], recurrence_months=12, lead_days=45, severity=2,
         penalty_sar=20000, penalty_note="",
         fix_steps=["راجع عقد جهة التخلص المرخّصة",
                    "حدّث سجلات النفايات",
                    "جدّد الترخيص أو التصريح"],
         evidence="عقد جهة التخلص + سجل النفايات", vip_code="VIP-LIC", source_url=""),
    # ---------------- Licences (all sectors) ----------------
    dict(code="LIC-BALADY", title="رخصة البلدية للنشاط التجاري", authority="وزارة الشؤون البلدية والقروية والإسكان — بلدي",
         category="التراخيص", scope="branch", packs=ALL, recurrence_months=12, lead_days=45, severity=2,
         penalty_sar=5000, penalty_note="",
         fix_steps=["افتح منصة بلدي وتحقق من حالة الرخصة والمخالفات",
                    "سدّد المخالفات والرسوم المستحقة",
                    "جدّد الرخصة وعلّقها في الفرع"],
         evidence="الرخصة سارية المفعول", vip_code="VIP-LIC",
         source_url="https://momah.gov.sa/en/node/15216"),
    dict(code="LIC-CD", title="شهادة السلامة (الدفاع المدني)", authority="الدفاع المدني — سلامة",
         category="التراخيص", scope="branch", packs=ALL, recurrence_months=12, lead_days=45, severity=3,
         penalty_sar=15000, penalty_note="التشغيل بعد الانتهاء يعرّض المنشأة للإغلاق عند أي تفتيش.",
         fix_steps=["احجز موعد فحص السلامة عبر منصة سلامة",
                    "عالج ملاحظات الفحص السابقة (طفايات، مخارج طوارئ، أنظمة الإنذار)",
                    "جدّد الشهادة بعد اجتياز الفحص"],
         evidence="شهادة السلامة سارية", vip_code="VIP-CD", source_url=""),
    dict(code="LIC-CR", title="تأكيد بيانات السجل التجاري", authority="وزارة التجارة",
         category="التراخيص", scope="branch", packs=ALL, recurrence_months=12, lead_days=30, severity=2,
         penalty_sar=3000, penalty_note="",
         fix_steps=["افتح خدمات وزارة التجارة وتحقق من حالة السجل",
                    "أكّد البيانات أو جدّد السجل",
                    "سدّد الرسوم واحفظ الإيصال"],
         evidence="شهادة السجل التجاري", vip_code="VIP-LIC", source_url=""),
    # ---------------- Tax / data ----------------
    dict(code="TAX-VAT", title="تقديم إقرار ضريبة القيمة المضافة", authority="هيئة الزكاة والضريبة والجمارك",
         category="الضرائب والزكاة", scope="branch", packs=ALL, recurrence_months=3, lead_days=10, severity=3,
         penalty_sar=10000, penalty_note="دورية الإقرار (شهرية/ربع سنوية) تعتمد على فئة المنشأة.",
         fix_steps=["جهّز الإقرار وطابق فواتير المبيعات والمشتريات",
                    "قدّم الإقرار عبر بوابة الهيئة",
                    "سدّد الضريبة المستحقة قبل الموعد"],
         evidence="إقرار مقدّم + إيصال سداد", vip_code="VIP-TAX", source_url=""),
    dict(code="TAX-ZAKAT", title="شهادة الزكاة", authority="هيئة الزكاة والضريبة والجمارك",
         category="الضرائب والزكاة", scope="branch", packs=ALL, recurrence_months=12, lead_days=60, severity=2,
         penalty_sar=10000, penalty_note="",
         fix_steps=["قدّم الإقرار الزكوي السنوي",
                    "سدّد المستحق",
                    "استخرج شهادة الزكاة"],
         evidence="شهادة الزكاة", vip_code="VIP-TAX", source_url=""),
    dict(code="DATA-PDPL", title="مراجعة سجل أنشطة معالجة البيانات الشخصية", authority="سدايا — نظام حماية البيانات الشخصية",
         category="حماية البيانات", scope="branch", packs=ALL, recurrence_months=12, lead_days=45, severity=2,
         penalty_sar=100000,
         penalty_note="الحد الأقصى المنشور للغرامة: حتى 5,000,000 ريال، وإبلاغ عن الاختراق خلال 72 ساعة.",
         fix_steps=["حدّث سجل أنشطة المعالجة وأنواع البيانات",
                    "راجع اتفاقيات معالجة البيانات مع الموردين",
                    "اختبر إجراء الإبلاغ عن الاختراق خلال 72 ساعة"],
         evidence="سجل المعالجة المحدّث", vip_code=None, source_url=""),
    # ---------------- Employee documents ----------------
    dict(code="EMP-IQAMA", title="تجديد الإقامة", authority="الجوازات — مقيم",
         category="وثائق الموظفين", scope="employee", packs=ALL, recurrence_months=12, lead_days=60, severity=2,
         penalty_sar=1000, penalty_note="",
         fix_steps=["افتح مقيم أو أبشر أعمال وتحقق من رسوم الإقامة ورخصة العمل",
                    "جدّد الإقامة قبل الانتهاء",
                    "حدّث النسخة في ملف الموظف"],
         evidence="نسخة الإقامة المجددة", vip_code="VIP-IQAMA", source_url=""),
    dict(code="EMP-WP", title="تجديد رخصة العمل", authority="وزارة الموارد البشرية — قوى",
         category="وثائق الموظفين", scope="employee", packs=ALL, recurrence_months=12, lead_days=60, severity=2,
         penalty_sar=2000, penalty_note="",
         fix_steps=["سدّد رسوم رخصة العمل والمقابل المالي",
                    "جدّد الرخصة عبر قوى",
                    "حدّث النسخة في ملف الموظف"],
         evidence="رخصة العمل المجددة", vip_code="VIP-IQAMA", source_url=""),
    dict(code="EMP-INS", title="تجديد التأمين الطبي", authority="مجلس الضمان الصحي",
         category="وثائق الموظفين", scope="employee", packs=ALL, recurrence_months=12, lead_days=30, severity=2,
         penalty_sar=1000, penalty_note="",
         fix_steps=["جدّد الوثيقة مع شركة التأمين قبل الانتهاء",
                    "أضف أي مستفيدين جدد",
                    "احفظ نسخة الوثيقة"],
         evidence="وثيقة التأمين السارية", vip_code="VIP-HEALTH", source_url=""),
    dict(code="EMP-HEALTH", title="تجديد الشهادة الصحية", authority="وزارة الشؤون البلدية والقروية والإسكان",
         category="وثائق الموظفين", scope="employee", packs=["hotel", "hospital"], recurrence_months=12, lead_days=30, severity=2,
         penalty_sar=500, penalty_note="",
         fix_steps=["احجز الفحص الطبي والتحاليل المطلوبة",
                    "أصدر أو جدّد الشهادة الصحية",
                    "احفظ نسخة في ملف الموظف"],
         evidence="الشهادة الصحية سارية", vip_code="VIP-HEALTH", source_url=""),
    dict(code="EMP-SCFHS", title="تجديد التصنيف المهني الصحي", authority="الهيئة السعودية للتخصصات الصحية",
         category="وثائق الموظفين", scope="employee", packs=["hospital"], recurrence_months=24, lead_days=90, severity=3,
         penalty_sar=5000, penalty_note="",
         fix_steps=["تأكد من ساعات التعليم الطبي المستمر المطلوبة",
                    "قدّم طلب التجديد عبر منصة الهيئة",
                    "حدّث ملف الممارس"],
         evidence="بطاقة التصنيف المهني", vip_code="VIP-HEALTHLIC", source_url=""),
    dict(code="EMP-CONTRACT", title="انتهاء عقد العمل محدد المدة", authority="وزارة الموارد البشرية — قوى",
         category="وثائق الموظفين", scope="employee", packs=ALL, recurrence_months=12, lead_days=30, severity=1,
         penalty_sar=500, penalty_note="",
         fix_steps=["قرّر التجديد أو الإنهاء قبل الانتهاء",
                    "وثّق القرار في قوى",
                    "أبلغ الموظف رسميًا"],
         evidence="العقد الموثق", vip_code=None, source_url=""),
]

# Changes: some are from earlier research (secondary sources) and are marked unverified.
# The last entry is a clearly labelled illustrative example to demo upcoming-effective-date alerts.
CHANGES = [
    dict(id=1, packs=ALL, title="برنامج نطاقات المطوَّر 2026–2028", authority="وزارة الموارد البشرية",
         published="2026-04-26", effective="2026-04-26",
         summary="مرحلة جديدة من نطاقات بنسب وحدود معدّلة لعدد من الأنشطة.",
         action_required="راجع نسبة التوطين المطلوبة لكل فرع مقابل النسبة الفعلية وحدّث خطة التوظيف.",
         affects=["HR-NITAQAT"], source_url="https://saudicomplianceinstitute.com/en/blogs/news/hospitality-compliance-2026-saudi-occupational-health-rules",
         source_quality="ثانوي", is_demo=0),
    dict(id=2, packs=["hotel"], title="توطين مهن الاستقبال والواجهة في المنشآت الفندقية", authority="وزارة الموارد البشرية / وزارة السياحة",
         published="2026-04-22", effective="2026-04-22",
         summary="اشتراط التوطين الكامل لعدد من وظائف الواجهة والاستقبال، ونسب دنيا لأقسام أخرى.",
         action_required="حدّد الوظائف المشمولة في كل فندق وطابقها مع الموظفين الحاليين.",
         affects=["HR-NITAQAT", "HR-WORKERDATA"], source_url="https://logiolegion.com/blogs/hotel-management-software-development-saudi-arabia",
         source_quality="ثانوي", is_demo=0),
    dict(id=3, packs=["hotel"], title="تحديث اشتراطات مرافق الضيافة السياحية", authority="وزارة الشؤون البلدية والقروية والإسكان",
         published="2025-09-10", effective="2025-09-10",
         summary="تحديث يشمل الموقع والتصميم والمتطلبات التشغيلية والنظافة والدفع الإلكتروني الآمن وإمكانية الوصول.",
         action_required="راجع اشتراطات الفرع مقابل التحديث قبل أي تجديد للرخصة.",
         affects=["LIC-BALADY", "LIC-MOT"], source_url="https://momah.gov.sa/en/node/15216",
         source_quality="رسمي", is_demo=0),
    dict(id=4, packs=["hotel"], title="تكثيف حملات التفتيش على تسجيل بيانات العاملين", authority="وزارة السياحة",
         published="2026-03-16", effective="2026-03-16",
         summary="حملات تفتيش على تسجيل وتحديث بيانات جميع العاملين (بمن فيهم عمالة شركات التشغيل) كل ثلاثة أشهر.",
         action_required="نفّذ تحديث البيانات الدوري لجميع الفروع قبل الموعد وتأكد من شمول عمالة المقاولين.",
         affects=["HR-WORKERDATA"], source_url="https://www.lexismiddleeast.com/news/2026-03-18_21/en",
         source_quality="ثانوي", is_demo=0),
    dict(id=5, packs=ALL, title="مثال توضيحي: تعديل موعد ملف حماية الأجور", authority="وزارة الموارد البشرية",
         published="2026-10-05", effective="2026-11-15",
         summary="مثال تجريبي لإظهار تنبيه تغيير تنظيمي له تاريخ سريان قادم. ليس قرارًا حقيقيًا.",
         action_required="مثال: حدّث موعد الرفع في تقويم المنشأة قبل تاريخ السريان.",
         affects=["HR-WPS"], source_url="", source_quality="مثال", is_demo=1),
]

VIP_SERVICES = [
    dict(code="VIP-LIC", name="تجديد تراخيص الفروع", description="نتولى تجديد البلدية والسجل والتراخيص القطاعية للفرع من الطلب حتى استلام الترخيص.",
         price_from=900, price_unit="للترخيص + الرسوم الحكومية", sla_days=5, packs=ALL),
    dict(code="VIP-CD", name="السلامة والدفاع المدني", description="حجز الفحص، ومعالجة الملاحظات، وتجديد شهادة السلامة.",
         price_from=1800, price_unit="للفرع + الرسوم الحكومية", sla_days=10, packs=ALL),
    dict(code="VIP-IQAMA", name="تجديد الإقامات ورخص العمل", description="تجديد الإقامة ورخصة العمل للموظفين قبل الانتهاء.",
         price_from=120, price_unit="للموظف + الرسوم الحكومية", sla_days=3, packs=ALL),
    dict(code="VIP-HEALTH", name="الشهادات الصحية والتأمين الطبي", description="إصدار وتجديد الشهادات الصحية ووثائق التأمين الطبي.",
         price_from=80, price_unit="للموظف + الرسوم", sla_days=3, packs=ALL),
    dict(code="VIP-NITAQAT", name="خطة معالجة نطاقات", description="تحليل الفجوة وإعداد خطة توظيف أو تحويل ومتابعتها حتى التحسن.",
         price_from=3500, price_unit="للمنشأة", sla_days=14, packs=ALL),
    dict(code="VIP-PAYROLL", name="الملفات الشهرية (مدد والتأمينات وقوى)", description="إعداد ورفع ملف الأجور والتأمينات وتوثيق العقود شهريًا.",
         price_from=1200, price_unit="شهريًا للفرع", sla_days=2, packs=ALL),
    dict(code="VIP-TAX", name="الإقرارات الضريبية والزكوية", description="إعداد الإقرار وتقديمه ومتابعة السداد.",
         price_from=1500, price_unit="للإقرار", sla_days=5, packs=ALL),
    dict(code="VIP-WORKERDATA", name="تحديث بيانات العاملين — وزارة السياحة", description="تحديث بيانات العاملين الفصلي في منصة الوزارة شاملًا عمالة المقاولين.",
         price_from=1000, price_unit="للفرع", sla_days=3, packs=["hotel"]),
    dict(code="VIP-HEALTHLIC", name="تراخيص واعتماد المنشآت الصحية", description="تجهيز ملفات الترخيص والتصنيف والاعتماد ومتابعتها.",
         price_from=4000, price_unit="للملف", sla_days=20, packs=["hospital"]),
]


# Names HR people actually use in exports, mapped to obligation codes (used by the CSV import; matched after
# normalisation: lower-case, collapsed spaces, hamza/ta-marbuta/ya variants folded, diacritics removed).
DOC_ALIASES = {
    "EMP-IQAMA": ["iqama", "residence", "residency permit", "اقامة", "الاقامة", "هوية مقيم", "تجديد الاقامة"],
    "EMP-WP": ["work permit", "workpermit", "رخصة عمل", "رخصة العمل", "تجديد رخصة العمل"],
    "EMP-INS": ["insurance", "medical insurance", "health insurance", "تامين", "تامين طبي", "التامين الطبي", "التامين"],
    "EMP-HEALTH": ["health certificate", "health card", "شهادة صحية", "الشهادة الصحية", "كرت صحي", "بطاقة صحية"],
    "EMP-CONTRACT": ["contract", "employment contract", "عقد", "عقد العمل", "العقد"],
    "EMP-SCFHS": ["scfhs", "professional classification", "تصنيف", "تصنيف مهني", "تصنيف الهيئة السعودية للتخصصات الصحية"],
    "LIC-MOT": ["tourism licence", "tourism license", "ترخيص سياحي", "ترخيص وزارة السياحة", "رخصة سياحية"],
    "LIC-MOH": ["moh licence", "moh license", "health facility licence", "ترخيص وزارة الصحة", "ترخيص المنشاة الصحية"],
    "ACC-CBAHI": ["cbahi", "سباهي", "اعتماد سباهي"],
    "LIC-WASTE": ["medical waste", "waste licence", "النفايات الطبية", "ترخيص النفايات"],
    "LIC-BALADY": ["balady", "baladiya", "municipal licence", "municipality licence", "رخصة بلدية", "رخصة البلدية", "بلدي", "رخصة نشاط تجاري"],
    "LIC-CD": ["civil defense", "civil defence", "salama", "الدفاع المدني", "شهادة السلامة", "سلامة"],
    "LIC-CR": ["commercial registration", "cr", "سجل تجاري", "السجل التجاري"],
    "TAX-ZAKAT": ["zakat", "zakat certificate", "الزكاة", "شهادة الزكاة"],
}


# ---------------------------------------------------------------------------------------------
# Domains, consequences and demo staff (all DEMO content; consequence wording is deliberately
# generic ("may ...") and stays unverified until a legal reviewer signs it off)
# ---------------------------------------------------------------------------------------------
DOMAIN_OVERRIDE = {"LIC-CD": "السلامة والدفاع المدني", "HR-OSH": "السلامة والدفاع المدني"}

CONSEQUENCES = {
    "HR-WPS": "عدم رفع الملف أو عدم مطابقته قد يُعرّض المنشأة لغرامات ويُقيّد بعض خدماتها في منصات الوزارة.",
    "HR-GOSI": "التأخر في السداد قد يترتب عليه غرامات تأخير ومطالبات من المؤسسة.",
    "HR-NITAQAT": "انخفاض النطاق قد يوقف خدمات المنشأة (التأشيرات ونقل الخدمات) إلى حين المعالجة.",
    "HR-QIWA": "العقود غير الموثقة قد لا تُعتمد عند النزاع أو التفتيش وقد تُعدّ مخالفة.",
    "HR-OSH": "قد تُسجَّل مخالفة عند التفتيش، وتتأثر مسؤولية المنشأة عند وقوع إصابة عمل.",
    "HR-WORKERDATA": "بيانات العمالة غير المحدّثة قد تعطّل إجراءات العمالة الوافدة وتعرّض المنشأة لمخالفة.",
    "LIC-MOT": "التشغيل بترخيص منتهٍ قد يعرّض المنشأة لغرامة وإيقاف النشاط.",
    "LIC-MOH": "التشغيل بترخيص منتهٍ قد يؤدي إلى غرامات أو إيقاف المنشأة الصحية.",
    "ACC-CBAHI": "عدم تجديد الاعتماد قد يؤثر على التعاقد مع شركات التأمين وعلى سمعة المنشأة.",
    "LIC-WASTE": "مخالفة التخلص من النفايات الطبية قد تعرّض المنشأة لغرامات وإجراءات رقابية.",
    "LIC-BALADY": "رخصة البلدية المنتهية قد تعرّض المنشأة لغرامة وإغلاق إداري.",
    "LIC-CD": "انتهاء شهادة السلامة قد يعرّض المنشأة لغرامة وإيقاف التشغيل، وقد يؤثر على التغطية التأمينية عند الحوادث.",
    "LIC-CR": "السجل التجاري المنتهي قد يوقف التعاملات والخدمات الحكومية للمنشأة.",
    "TAX-VAT": "التأخر في تقديم الإقرار قد يرتّب غرامات تأخير تتزايد مع المدة.",
    "TAX-ZAKAT": "التأخر في تقديم الإقرار قد يرتّب غرامات تأخير ويؤثر على الشهادات المطلوبة للتعاقد.",
    "DATA-PDPL": "مخالفة نظام حماية البيانات الشخصية قد تعرّض المنشأة لعقوبات وتضر بثقة العملاء.",
    "EMP-IQAMA": "عامل بإقامة منتهية قد يعرّض المنشأة لغرامة عن كل عامل ويعطّل خدماته.",
    "EMP-WP": "عامل بلا رخصة عمل سارية قد يُحتسب مخالفة على المنشأة.",
    "EMP-INS": "غياب التأمين الطبي الساري قد يوقف إجراءات العامل ويُحتسب مخالفة.",
    "EMP-HEALTH": "عاملون في الأغذية بلا شهادة صحية سارية قد يعرّضون المنشأة لمخالفة عند التفتيش.",
    "EMP-SCFHS": "ممارس بتصنيف منتهٍ قد لا يُسمح له بالممارسة وقد تُحتسب مخالفة.",
    "EMP-CONTRACT": "عقد منتهٍ دون تجديد قد يضعف موقف المنشأة في أي نزاع عمالي.",
}

# Named people exist only for the three seeded demo organisations; imported organisations get role titles only.
DEMO_STAFF = {
    "مجموعة الواحة للفنادق": dict(gm="عبدالله الدوسري", hr="نورة العتيبي", branches=["فهد الشمري", "سلطان الحربي", "ماجد الزهراني"]),
    "مستشفى الرعاية التخصصي": dict(gm="خالد القحطاني", hr="ريم السبيعي", branches=["يوسف الغامدي", "هند المطيري"]),
    "شركة الأفق للمقاولات": dict(gm="ناصر الشريف", hr="منى العنزي", branches=["طارق الخان", "وليد الدوسري", "بدر الحربي"]),
}
